### PR TITLE
Refactor extraction script, add script to update other languages

### PR DESCRIPTION
**Pull request by flodolo**
I tried to keep the commits as self-contained as possible.

### CODE REVIEW

**Comment by flodolo** [comment]
Background: turns out Pontoon isn't happy when you add strings only to en-US, but I think that [behavior should be changed](https://bugzilla.mozilla.org/show_bug.cgi?id=1676336). That's why I kept two separate files, so it will be really easy to remove the script that updates other languages.

**Comment by flodolo** [comment]
Currently fighting with GitHub actions to make it see `pip`.

**Comment by flodolo** [comment]
I'm running out of ideas, I'm practically using the code from their docs, but it fails to find `pip`
https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-python#starting-with-the-python-workflow-template

**Comment by flodolo** [comment]
I finally made it work ([log](https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/runs/1379226271?check_suite_focus=true)). Apparently the `debian` image doesn't have a working `pip`? Not even `$(which pip)` worked.

I've created a test pull request, but I'm not exactly sure where the additional `xmlns:trolltech="urn:trolltech:names:ts:document:1.0"` comes from, and if it's an issue.

**Comment by flodolo** [comment]
> I've created a test pull request, but I'm not exactly sure where the additional `xmlns:trolltech="urn:trolltech:names:ts:document:1.0"` comes from, and if it's an issue.

OK, I see where that was fixed in the old file. I need to figure out how to do it with lxml.

**Comment by flodolo** [comment]
Fixed the namespace. The diff on the English file is about reordering attributes in the file element, and I think that's OK (it's a one time thing).

There seems to be a problem with `Update Now` string, but I don't think that's connected to my work

> lupdate warning: Message with id 'vpn.updates.updateNow' has no source.

I'll try running to master to confirm if I see the same diff.

**Comment by flodolo** [comment]
> I'll try running from master to confirm if I see the same diff.

The script from master doesn't have that difference. Can it be a different version of `qt` between the Debian image and plain Ubuntu-latest? Which one is correct?

I have a Ubuntu 20.04 VM with `5.2.18`, and I don't see that error.

**Comment by flodolo** [comment]
Version of QT:
* In the `debian` image (the one currently used in master), is `5.11.3`, and newline characters are exported as `\n`.
* In `ubuntu-latest` is `5.9.5`, and there are several errors when running the update (see the *Extract new strings* section in [this log](https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/runs/1379597178?check_suite_focus=true)).
* In `ubuntu-20.04` is `5.2.18`, and there's no issue with the ”Update Now" strings. Newline characters are exposed as new lines in both the .ts and .xliff files.

This is the export of the current version of the code (5.2.18)
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/44/files

Is it OK to use actual new lines? If so, we need to amend the comments.

**Comment by flodolo** [comment]
I just noticed that the [README](https://github.com/mozilla-mobile/mozilla-vpn-client/blob/master/README.md) says Qt5 >= 5.15.0. I think the closest we can get with the default packages is 5.14 ([with Ubuntu 20.10](https://packages.ubuntu.com/groovy/libs/qt5-default)).

**Comment by flodolo** [comment]
The manual compilation instructions from the README seem overkill (I tried locally, and it's a 500+ MB package to download). Looks like using the external ppa for 5.15 works (5.15.1 is not available). 

Still getting the `\n` converted to actual linefeeds, and at this point I expect that's correct.
https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/pull/47/files

**Review by bakulf — APPROVED** [review]

**Comment by flodolo** [comment]
Merging per conversation with baku on Slack.

**Pull request merged**
